config/routes.rb
DealSite::Application.routes.draw do
  resources :advertisers do
    resource :publisher
  end

  resources :deals do
    resource :advertiser
  end

  resources :publishers do
    resources :advertisers
  end

  match '/' => 'publishers#index', :as => :root
end

app/models/advertiser.rb
class Advertiser < ActiveRecord::Base
  has_many :deals
  belongs_to :publisher

  validates_presence_of :name
  validates_uniqueness_of :name

  validates_presence_of :publisher
end

app/models/deal.rb
class Deal < ActiveRecord::Base
  belongs_to :advertiser

  validates_presence_of :advertiser, :value, :price, :description, :start_at, :end_at

  def over?
    Time.zone.now > end_at
  end

  def savings_as_percentage
    0.5
  end

  def savings
    20
  end
end

app/models/publisher.rb
class Publisher < ActiveRecord::Base
  has_many   :advertisers
  belongs_to :parent, class_name: "Publisher"
  has_many   :publishers, foreign_key: :parent_id
  validates  :name, :uniqueness => true

  validate :parent_is_another_publisher

  def parent_is_another_publisher
    if parent && parent == self
      errors.add :parent, " cannot be self"
    end
    true
  end

  def get_theme
    p = self
    p = p.parent while !p.theme and p.parent
    p.theme
  end
end

app/controllers/advertisers_controller.rb
class AdvertisersController < ApplicationController
  def index
    @publisher = Publisher.find(params[:publisher_id])
    @advertisers = @publisher.advertisers
  end

  def new
    @advertiser = Advertiser.new
    @publisher = Publisher.find(params[:publisher_id])
  end

  def edit
    @advertiser = Advertiser.find(params[:id])
  end

  def create
    @advertiser = Advertiser.new(params[:advertiser])

    if @advertiser.save
      redirect_to edit_advertiser_path(@advertiser), notice: 'Advertiser was successfully created.'
    else
      render action: "new"
    end
  end

  def update
    @advertiser = Advertiser.find(params[:id])

    if @advertiser.update_attributes(params[:advertiser])
      redirect_to edit_advertiser_path(@advertiser), notice: 'Advertiser was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @advertiser = Advertiser.find(params[:id])
    @advertiser.destroy
    redirect_to publisher_advertisers_path(@advertiser.publisher)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
  before_filter :assign_deal, only: [ :show, :edit, :update, :destroy ]
  before_filter :set_view_paths, only: :show

  def index
    @deals = Deal.all(include: {advertiser: {publisher: :parent}}, order: :id)
  end

  def show
    respond_to do |format|
      format.html { render layout: "deals/show" }
      format.json { render json: @deal }
    end
  end

  def new
    @advertiser = Advertiser.find(params[:advertiser_id])
    @deal = @advertiser.deals.build
  end

  def create
    @advertiser = Advertiser.find(params[:advertiser_id])
    @deal = @advertiser.deals.build(params[:deal])
    if @deal.save
      redirect_to edit_deal_path(@deal), notice: 'Deal was successfully created.'
    else
      render action: "new"
    end
  end

  def update
    if @deal.update_attributes(params[:deal])
      redirect_to edit_deal_path(@deal), notice: 'Deal was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @deal.destroy
    redirect_to deals_url
  end

  protected

  def assign_deal
    @deal = Deal.find(params[:id])
  end

  def set_view_paths
    publisher = @deal.advertiser.publisher
    theme = publisher.get_theme
    @publisher_name = publisher.name
    prepend_view_path "app/themes/#{theme}/views"
  end
end

app/controllers/publishers_controller.rb
class PublishersController < ApplicationController
  def index
    @publishers = Publisher.all
  end

  def new
    @publisher = Publisher.new(params[:publisher])
    render :edit
  end

  def create
    @publisher = Publisher.new(params[:publisher])

    if @publisher.save
      redirect_to edit_publisher_path(@publisher), notice: 'Publisher was successfully created.'
    else
      render action: "new"
    end
  end

  def edit
    @publisher = Publisher.find(params[:id])
  end

  def update
    @publisher = Publisher.find(params[:id])
    if @publisher.update_attributes(params[:publisher])
      flash[:notice] = "Updated #{@publisher.name}"
      redirect_to edit_publisher_path(@publisher)
    else
      render :edit
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def cache_key(controller, view, object)
    object ? '%s__%s__%s%d' % [controller, view, object.class, object.id] : '%s__%s' % [controller, view]
  end
end

app/helpers/deals_helper.rb
module DealsHelper
end

app/helpers/publishers_helper.rb
module PublishersHelper
  def publisher_names(publisher)
    publisher.parent ? "#{publisher.parent.name} #{publisher.name}" : publisher.name
  end
end

app/views/advertisers/_form.html.erb
<%= form_for(@advertiser) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/advertisers/edit.html.erb
<h1><%= @advertiser.publisher.name %> <%= @advertiser.name %></h1>

<%= render 'form' %>

app/views/advertisers/index.html.erb
<h1><%= @publisher.name %> Advertisers</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Belongs to</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
<% @advertisers.each do |advertiser| %>
    <tr>
      <td><%= advertiser.name %></td>
      <td><%= link_to 'Edit', edit_advertiser_path(advertiser) %></td>
      <td><%= link_to 'Destroy', advertiser, confirm: 'Are you sure?', method: :delete %></td>
    </tr>
  </tbody>
<% end %>
</table>

<br />

<%= link_to 'New Advertiser', new_publisher_advertiser_path(@publisher) %>

app/views/advertisers/new.html.erb
<h1>New advertiser</h1>

<%= render 'form' %>

app/views/deals/_form.html.erb
<%= form_for(@deal) do |f| %>
  <% if @deal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@deal.errors.count, "error") %> prohibited this deal from being saved:</h2>

      <ul>
      <% @deal.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :proposition %>
  <%= f.text_field :proposition %>

  <%= f.label :value %>
  <%= f.number_field :value %>

  <%= f.label :inventory %>
  <%= f.number_field :inventory %>

  <%= f.label :price %>
  <%= f.number_field :price %>

  <%= f.label :description %>
  <%= f.text_area :description %>

  <%= f.label :start_at %>
  <%= f.datetime_select :start_at %>

  <%= f.label :end_at %>
  <%= f.datetime_select :end_at %>

  <%= f.label :sold_out %>
  <%= f.check_box :sold_out %>

  <%= f.submit %>
<% end %>

app/views/deals/edit.html.erb
<h1>Editing deal</h1>

<%= render 'form' %>

<%= link_to 'Show', @deal %>

app/views/deals/index.html.erb
<%-
cache(cache_key('deals', 'index', nil)) do
-%>
<h1>Deals</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Proposition</th>
      <th>Value</th>
      <th>Price</th>
      <th>Description</th>
      <th>Advertiser</th>
      <th>Publisher</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>

<%-
  @deals.each do |deal|
    cache(cache_key('deals', 'index', deal)) do
-%>
    <tr>
      <td><%= deal.proposition %></td>
      <td><%= deal.value %></td>
      <td><%= deal.price %></td>
      <td><%= deal.description %></td>

    <%-
      advertiser = deal.advertiser
      cache(cache_key('deals', 'index', advertiser)) do
    -%>
      <td><%= advertiser.name %></td>
      <td><%= publisher_names(advertiser.publisher) %></td>
    <%- end -%>

      <td><%= link_to 'Show', deal %></td>
      <td><%= link_to 'Edit', edit_deal_path(deal) %></td>
      <td><%= link_to 'Destroy', deal, confirm: 'Are you sure?', method: :delete %></td>
    </tr>
<%-
    end
  end
-%>

  </tbody>
</table>

<br />

<%= link_to 'New Deal', new_deal_path %>
<%-
end
-%>

app/views/deals/new.html.erb
<h1>New deal</h1>

<%= render 'form' %>

app/views/deals/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @deal.proposition %></h1>

<h2>$<%= @deal.value %> Value for Only $<%= @deal.price %></h2>

<h3>Deal ends at <%= @deal.end_at.to_s(:long) %></h3>

<p>
  <%= @deal.description %>
</p>

<h3>Only <span class="inventory"><%= @deal.inventory %></span> Left</h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Deal Site</title>
 
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->


  <%= stylesheet_link_tag    "bootstrap", :media => "all" %>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tag %>

  <link rel="shortcut icon" href="images/favicon.ico">
  <link rel="apple-touch-icon" href="images/apple-touch-icon.png">
  <link rel="apple-touch-icon" sizes="72x72" href="images/apple-touch-icon-72x72.png">
  <link rel="apple-touch-icon" sizes="114x114" href="images/apple-touch-icon-114x114.png">

</head>
<body>
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="/">Home</a>
        <div class="nav-collapse">
          <ul class="nav">
            <li><a href="/">Publishers</a></li>
            <li><a href="/deals">Deals</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
  </div>

    <div class="container">
      <% if flash[:warn].present? %>
      <div class="row">
        <div class="span16">
          <div class="alert-message warning">
            <p><%= flash[:warn] %></p>
          </div>
        </div>
      </div>
      <% end %>

      <% if flash[:notice].present? %>
      <div class="row">
        <div class="span16">
          <div class="alert-message success">
            <p><%= flash[:notice] %></p>
          </div>
        </div>
      </div>
      <% end %>

<%= yield %>

      <footer>
        <p>&copy; Deal Site 2012</p>
      </footer>

    </div> <!-- /container -->
</body>
</html>

app/views/layouts/deals/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @deal.proposition %></title>
 
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->


  <%= stylesheet_link_tag    "bootstrap.min", :media => "all" %>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tag %>

  <link rel="shortcut icon" href="images/favicon.ico">
  <link rel="apple-touch-icon" href="images/apple-touch-icon.png">
  <link rel="apple-touch-icon" sizes="72x72" href="images/apple-touch-icon-72x72.png">
  <link rel="apple-touch-icon" sizes="114x114" href="images/apple-touch-icon-114x114.png">

</head>
<body>
    <div class="container">
      <% if flash[:warn].present? %>
      <div class="row">
        <div class="span16">
          <div class="alert-message warning">
            <p><%= flash[:warn] %></p>
          </div>
        </div>
      </div>
      <% end %>

      <% if flash[:notice].present? %>
      <div class="row">
        <div class="span16">
          <div class="alert-message success">
            <p><%= flash[:notice] %></p>
          </div>
        </div>
      </div>
      <% end %>

<%= yield %>

    </div> <!-- /container -->
</body>
</html>

app/views/publishers/_publisher.html.erb
<tr>
  <td><%= publisher.name %></td>
  <td><%= publisher.theme %></td>
  <td><%= link_to "Advertisers", publisher_advertisers_path(publisher) %></td>
  <td><%= link_to "Edit", edit_publisher_path(publisher) %></td>
</tr>

app/views/publishers/edit.html.erb
<h1>Publisher: <%= @publisher.name %></h1>

<%= form_for(@publisher) do |f| %>
  <label>Name</label>
  <%= f.text_field :name %>

  <label>Theme</label>
  <%= f.text_field :theme %>

  <!-- Moved to Deal? Don't think we still need this. SW: Jun 3, 2008 -->
  <!-- <label>City</label> -->
  <%#= f.text_field :city %>

  <%= f.submit %>
<% end %>

app/views/publishers/index.html.erb
<h1>Publishers</h1>

<table class="publishers table table-striped">
  <thead>
    <th>Name</th>
    <th>Label</th>
    <th/>
    <th/>
  </thead>
  <tbody>
<%= render @publishers.sort_by(&:name) %>
  </tbody>
</table>

<p>
  <%= link_to "New Publisher", new_publisher_path %>
</p>